name: "Release"
description: 'Publishes python package to PyPI'

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Poetry
      shell: bash
      run: pip install --no-input poetry

    - name: Publish to PyPI
      shell: bash
      env:
        PYPI_TOKEN: ${{ inputs.registry-token }}
      run: |
        poetry publish --build --username __token__ --password $PYPI_TOKEN
